import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/styles/style.css"
import "@/scripts/script.js"
import Header from "@/components/layout/header/Header";
import Footer from "@/components/layout/footer/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="d-flex justify-content-between">
        <Header/>
          <div className="blog-container d-flex justify-content-between flex-column align-items-center">
          {children}
           <Footer/>
          </div>
        </div>
        </body>
      {/* <script src="js/jquery.min.js"></script>
      <script src="js/templatemo-script.js"></script> */}
    </html>
  );
}
